# Generated by Django 5.1 on 2024-08-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='date',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
