# Generated by Django 5.1 on 2024-08-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_user_alter_date_created_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='key',
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app2.item'),
        ),
    ]
