# Generated by Django 5.1 on 2024-08-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
