# Generated by Django 5.1 on 2024-08-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_alter_login_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='user_name',
            new_name='username',
        ),
    ]
