# Generated by Django 5.1 on 2024-08-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_rename_user_password_login_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='user_password',
        ),
    ]
