# Generated by Django 5.1 on 2024-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_rename_username_login_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
