# Generated by Django 5.1 on 2024-08-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'Mart Product'},
        ),
    ]
