# Generated by Django 5.1 on 2024-08-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_client_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client_name',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
